### ISSUE TITLE
Ardublockly building problem

### ISSUE THREAD

**Issue by ioarvanit** [carlosperate/ardublockly#160] opened 2017-03-26 19:35 UTC
Hi. I have just downloaded the ardublockly-master and i can't build the windows executable.

I made some minor changes to blockly blocks and generators and succesfully build blockly. I am running localy ardublockly with python server and everything works fine.

The problem occurs when i try to build a new windows executable, I followed the instructions at https://github.com/carlosperate/ardublockly/wiki/Building-Ardublockly and when i run the build_py2exe.py script i get an empty arduexec folder and some traceback calls in the command line. (see image below)

I have python 2.7 and 3.6 installed, and i also installed py2exe, pyInstaller, MkDocs and node.js with electron. I have windows 10 32-bit. I would really appreciate any help on this!

![default](https://cloud.githubusercontent.com/assets/22624689/24334489/a9477f9e-1273-11e7-96fb-3a91d765a243.png)

**Comment by carlosperate** [comment] 2017-04-02 11:57
Hi @ioarvanit,

Apologies for the late reply. It looks like py2exe does not yet support python 3.6, and in fact is not yet compatible with python 3.5 either, so it looks like for the time being Python 3.4 will be required to build Ardublockly.

**Comment by carlosperate** [comment] 2017-04-02 12:02
I've also added a note in https://github.com/carlosperate/ardublockly/wiki/Building-Ardublockly to emphasise this incompatibility.

**Comment by ioarvanit** [comment] 2017-04-06 20:43
Thanks for the feedback.

**Comment by carlosperate** [comment] 2017-04-17 23:49
Closing this as the issue is an incompatibility from py2exe and the Python version.

**Closed by carlosperate** 2017-04-17 23:49 UTC
Labels: server, windows
