### ISSUE TITLE
TypeError: LoadLibrary() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by hhernandez92** [carlosperate/ardublockly#147] opened 2017-02-06 17:45 UTC
After following the procedures on https://github.com/carlosperate/ardublockly/wiki/Building-Ardublockly and trying to launch "start.py", an exception is thrown: "TypeError: LoadLibrary() argument 1 must be string, not unicode".

I'm currently running python 2.7

**Comment by hhernandez92** [comment] 2017-02-06 17:50
I was able to solve the issue by changing the following lines of code in "list_ports_windows.py"

Line 83: 
From - setupapi = ctypes.windll.LoadLibrary("setupapi")
To - setupapi = ctypes.windll.LoadLibrary("setupapi".encode('ascii', 'ignore'))

and Line 113:
From - advapi32 = ctypes.windll.LoadLibrary("Advapi32")
To - advapi32 = ctypes.windll.LoadLibrary("Advapi32".encode('ascii', 'ignore'))

**Comment by emil01** [comment] 2017-02-12 13:44
@hhernandez92 Not exactly sure why the issue is but I resolved it by running start.py using python3

**Comment by carlosperate** [comment] 2017-04-15 22:39
Turns out to be a bug in Python 2.7.13, so the best options right now are to either user an earlier 2.7 version, or move to Python 3.
I'll close this here as no changes are required in the Ardublockly repository.

**Closed by carlosperate** 2017-04-15 22:39 UTC
